name: Class-Adapter
version: 0.02
abstract: Perl implementation of the Adapter Design Pattern
author: Adam Kennedy<adam@ali.as>
license: unknown
distribution_type: module
build_requires:
  File::Spec: 0.82
  Test::More: 0.47
requires:
  perl: 5.005
  Scalar::Util: 1.10
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.36
