---
abstract: "Perl implementation of the \"Adapter\" Design Pattern"
author:
  - 'Adam Kennedy <adamk@cpan.org>'
build_requires:
  Test::More: 0.47
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Class::Adapter
name: Class-Adapter
no_index:
  directory:
    - inc
    - t
requires:
  Scalar::Util: 1.10
  perl: 5.005
resources:
  license: http://dev.perl.org/licenses/
version: 1.05
